// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKip7_kX_qFaSIpskWjyBFFeuknwyEri0',
    appId: '1:607159590701:web:fade7d26ac8c045300fda4',
    messagingSenderId: '607159590701',
    projectId: 'bright-future-foundation-5d630',
    authDomain: 'bright-future-foundation-5d630.firebaseapp.com',
    storageBucket: 'bright-future-foundation-5d630.firebasestorage.app',
    measurementId: 'G-E56HPMM3YR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFEl-mWjC4bZcVGOhXX4W-YBUQLrLSFlg',
    appId: '1:607159590701:android:52b40f704f2a880700fda4',
    messagingSenderId: '607159590701',
    projectId: 'bright-future-foundation-5d630',
    storageBucket: 'bright-future-foundation-5d630.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSVL-xt1VgXmzpXzM-PDqyBfnFoAg1cw8',
    appId: '1:607159590701:ios:f369a3ede845215500fda4',
    messagingSenderId: '607159590701',
    projectId: 'bright-future-foundation-5d630',
    storageBucket: 'bright-future-foundation-5d630.firebasestorage.app',
    iosBundleId: 'com.example.bright',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSVL-xt1VgXmzpXzM-PDqyBfnFoAg1cw8',
    appId: '1:607159590701:ios:f369a3ede845215500fda4',
    messagingSenderId: '607159590701',
    projectId: 'bright-future-foundation-5d630',
    storageBucket: 'bright-future-foundation-5d630.firebasestorage.app',
    iosBundleId: 'com.example.bright',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKip7_kX_qFaSIpskWjyBFFeuknwyEri0',
    appId: '1:607159590701:web:6286da19bb7eec1900fda4',
    messagingSenderId: '607159590701',
    projectId: 'bright-future-foundation-5d630',
    authDomain: 'bright-future-foundation-5d630.firebaseapp.com',
    storageBucket: 'bright-future-foundation-5d630.firebasestorage.app',
    measurementId: 'G-Q6Y7SBGB5S',
  );

}